### PR TITLE
Improve the regex, require Node.js 8

### LINKED ISSUE #7: `v` prefix is not part of semver
`'v1.0.0'.match(semverRegex())` returns `['v1.0.0']` but should be `['1.0.0']`.

### LINKED ISSUE #14: This regex is broken by design
Test it against the following data set, it will pass some non-conforming strings and fail to pass some that are conforming.

1.2.3----RC-SNAPSHOT.12.9.1--.12
1.0.0+0.build.1-rc.10000aaa-kk-0.1
99999999999999999999999.999999999999999999.99999999999999999
Begin Invalid

1
1.2
1.2.3-0123
1.2.3-0123.0123
1.1.2+.123
+invalid
-invalid
-invalid+invalid
-invalid.01
alpha
alpha.beta
alpha.beta.1
alpha.1
alpha+beta
alpha_beta
alpha.
alpha..
beta\
1.0.0-alpha_beta
-alpha.
1.0.0-alpha..
1.0.0-alpha..1
1.0.0-alpha...1
1.0.0-alpha....1
1.0.0-alpha.....1
1.0.0-alpha......1
1.0.0-alpha.......1
01.1.1
1.01.1
1.1.01
1.2
1.2.3.DEV
1.2-SNAPSHOT
1.2.31.2.3----RC-SNAPSHOT.12.09.1--..12+788
1.2-RC-SNAPSHOT
-1.0.3-gamma+b7718
+justmeta
9.8.7+meta+meta
9.8.7-whatever+meta+meta
99999999999999999999999.999999999999999999.99999999999999999----RC-SNAPSHOT.12.09.1--------------------------------..12

See semver/semver/issues/59.

### PR DESCRIPTION
**Pull request by stroncium**
- Added invalid strings from #14
- Made regexp respect Semantic Versioning 2.0.0 clause 9
- Made regexp to only respect boundaries to whitespace and beginnings/ends of strings

- Changed older tests to not violate clause 9
`'1.2.3-alpha.10.beta.0', '1.2.3-alpha.10.beta.0+build.unicorn.rainbow'`
became 
`'1.2.3-alpha.10.beta', '1.2.3-alpha.10.beta+build.unicorn.rainbow'`

- Fixed #7 while I was at it.

- [WIP] nodejs v6

---

Fixes #14
Fixes #7

### CODE REVIEW

**Comment by stroncium** [comment]
@sindresorhus Both this fixes aren't possible without lookbehind assertions, which aren't available in Node.js v6 without `--harmony` flag. Current state of package is clearly bad and dangerous, as it matches things like `O.1.1.1`(note it starts with O, not zero) without asking. So, my proposal will be to fall back to old behavior and print a notice to stderr in case we run without `--harmony`.

**Comment by stroncium** [comment]
@sindresorhus Both fixes aren't possible without lookbehind assertions, which aren't available in Node.js v6 without `--harmony` flag. I bumped min version to 8.

**Comment by sindresorhus** [comment]
Awesome! :)

**Comment by sindresorhus** [comment]
@stroncium This PR introduces catastrophic backtracking to the regex. Specifically this part `(?=$|\s)`. 

I have worked around it for now, but it would be great if you could try to bring back the old functionality: https://github.com/sindresorhus/semver-regex/commit/6baf2cc1d470c2fb63666bdebeef06822be7ba8c

Playground: https://regex101.com/r/X20eYT/2

**Pull request merged**
